### PR TITLE
ganache-cli in CI pipeline

### PR DESCRIPTION
**Pull request by ggwpez**
Trying to get the `TestNodes` test working.

### CODE REVIEW

**Comment by ggwpez** [comment]
As long as this [bug](https://github.com/c-bata/go-prompt/pull/172) is not fixed, the automated node testing does not work.  
We either 1. Fork go-prompt,  
2. Use the `TestAPI` RPC to send the commands instead of goexpect,  
3. wait for c-bata to merge it :sleeping_bed:

**Comment by sebastianst** [comment]
I pushed this problem in the go-prompt repo (https://github.com/c-bata/go-prompt/issues/39). I propose that we wait a bit for him to hopefully fix it soon.

**Comment by matthiasgeihs** [comment]
i experimented with replacing goexpect by some simple os/exec logic. this failed, however, because go-prompt is used in the demo and this relies on the low level system specific implementation and does not use the regular stdin stdout for interfacing with the command line user.

**Comment by ggwpez** [comment]
Ci got fixed in #26

**Pull request closed without merging**
